--- CREATE TABLE ---

CREATE TABLE SUBSCRIPTIONS(
USERID INT PRIMARY KEY,
PLANTYPE VARCHAR(20),
MONTHLYFEE INT,
MONTHSACTIVE INT,
UPGRADED VARCHAR(20),
COUNTRY VARCHAR(20),
DEVICE VARCHAR(20),
CHURNED VARCHAR(20)
);

--- INSER VALUES INTO IT ---

INSERT INTO SUBSCRIPTIONS VALUES
(90001,'BASIC',200,6,'NO','INDIA','MOBILE','NO'),
(90002,'STANDARD',400,12,'YES','USA','DESKTOP','NO'),
(90003,'PREMIUM',600,8,'NO','INDIA','TV','NO'),
(90004,'BASIC',200,3,'YES','UK','MOBILE','YES'),
(90005,'STANDARD',400,10,'NO','INDIA','DESKTOP','NO'),
(90006,'PREMIUM',600,5,'YES','USA','TV','NO'),
(90007,'BASIC',200,4,'NO','INDIA','MOBILE','YES'),
(90008,'STANDARD',400,9,'YES','UK','DESKTOP','NO'),
(90009,'PREMIUM',600,7,'NO','INDIA','TV','NO'),
(90010,'BASIC',200,2,'YES','USA','MOBILE','YES')

--- SEE WHOLE DATA ---

SELECT * 
FROM SUBSCRIPTIONS;

--- REVENUE ---

SELECT 
  PLANTYPE,
  SUM(MONTHLYFEE*MONTHSACTIVE) AS TOTAL_REVENUE
FROM SUBSCRIPTIONS
GROUP BY PLANTYPE
ORDER BY TOTAL_REVENUE DESC;

--- UPGRADEFLAG ANALYSIS ---

SELECT 
  COUNTRY,
  COUNT(CASE WHEN UPGRADED = 'YES' THEN 1 END) AS UPGRADEFLAG
FROM SUBSCRIPTIONS
GROUP BY COUNTRY
ORDER BY UPGRADEFLAG DESC;

--- CHURN ANALYSIS ---

SELECT 
 PLANTYPE,
 COUNT(CASE WHEN CHURNED = 'YES' THEN 1 END) AS CHURNRATE
FROM SUBSCRIPTIONS
GROUP BY PLANTYPE
ORDER BY CHURNRATE DESC;

--- HIGH - VALUE USERS ---

SELECT *
FROM SUBSCRIPTIONS
WHERE MONTHLYFEE*MONTHSACTIVE >3000;

--- LOW - VALUE USERS ---

SELECT *
FROM SUBSCRIPTIONS
WHERE MONTHLYFEE*MONTHSACTIVE <=3000;

