--- CREATE DB ---

CREATE DATABASE TASKS;

--- CREATE TABLE ---

CREATE TABLE FOOD_ORDERS(
ORDERID INT PRIMARY KEY,
RESTAURANT VARCHAR(20),
CITY VARCHAR(20),
DISTANCE_KM INT,
DELIVERYTIME_MIN INT,
PREPTIME_MIN INT,
DELIVERYPATNERRATING FLOAT,
LATEDELIVERY VARCHAR(20)
);

--- INSERT VALUES INTO IT ---

INSERT INTO FOOD_ORDERS VALUES

(3001,'BURGER HUB','DELHI',3,30,15,4.5,'NO'),
(3002,'PIZZA POINT','MUMBAI',5,50,20,4.2,'YES'),
(3003,'SPICE KITCHEN','DELHI',2,25,12,4.8,'NO'),
(3004,'BURGER HUB','BANGALORE',6,55,18,4.0,'YES'),
(3005,'PIZZA POINT','DELHI',4,40,15,4.3,'NO'),
(3006,'SPICE KITCHEN','MUMBAI',7,60,22,3.9,'YES'),
(3007,'BURGER HUB','MUMBAI',3,35,14,4.6,'NO'),
(3008,'PIZZA POINT','BANGALORE',8,70,25,3.8,'YES'),
(3009,'SPICE KITCHEN','DELHI',2,20,1,4.9,'NO'),
(3010,'BURGER HUB','DELHI',5,45,16,4.2,'YES')

--- VIEW DATA ---

SELECT * FROM FOOD_ORDERS;

--- LATE DELIVERY RATE ---

SELECT 
 COUNT(CASE WHEN LATEDELIVERY = 'YES' THEN 1 END)*100.0/COUNT(*) AS LATEDELIVERY_RATE
FROM FOOD_ORDERS;

--- RESTAURANT PERFORMANCE ---

SELECT 
 RESTAURANT,
 COUNT(*) AS TOTAL_ORDERS,
 SUM(CASE WHEN LATEDELIVERY = 'YES' THEN 1 ELSE 0 END) AS LATE_ORDERS
FROM FOOD_ORDERS
GROUP BY RESTAURANT
ORDER BY TOTAL_ORDERS DESC;

--- DISTANCE IMPACT ---

SELECT 
  AVG(DISTANCE_KM) AS AVG_DISTANCE,
  AVG(DELIVERYPATNERRATING) AS AVG_RATING
FROM FOOD_ORDERS
GROUP BY DISTANCE_KM
ORDER BY AVG_RATING DESC;

--- CITY ANALYSIS ---

SELECT 
  CITY,
  AVG(DELIVERYTIME_MIN) AS AVG_DELIEVRYTIME
FROM FOOD_ORDERS
GROUP BY CITY
ORDER BY AVG_DELIEVRYTIME DESC;

