--- CREATE TABLE ---

CREATE TABLE GYM_VISITS(
MEMBERID VARCHAR(10) PRIMARY KEY,
MEMBERSHIPPLAN VARCHAR(10),
MONTHLYFEE INT,
GYMVISITS_PERMONTH INT,
PERSONAL_TRAINING_SESSIONS INT,
FITNESSRATING INT,
MEMBERSHIP_DURATION_MONTHS INT,
CANCELLED VARCHAR(10)
);

--- INSERT DATA ---

INSERT INTO GYM_VISITS VALUES
('G1001','BASIC',999,5,0,2,3,'YES'),
('G1002','PREMIUM',3499,18,6,5,18,'NO'),
('G1003','STANDARD',1999,10,2,4,9,'NO'),
('G1004','BASIC',999,4,0,1,2,'YES'),
('G1005','PREMIUM',3499,22,8,5,24,'NO'),
('G1006','STANDARD',1999,8,1,3,7,'YES'),
('G1007','BASIC',999,6,0,2,4,'YES'),
('G1008','PREMIUM',3499,20,7,5,20,'NO'),
('G1009','STANDARD',1999,11,3,4,10,'NO'),
('G1010','BASIC',999,3,0,1,1,'YES')

--- VIEW DATA ---

SELECT * FROM GYM_VISITS;

--- OVERALL CHURN RATE ---

SELECT 
 AVG(CASE WHEN CANCELLED = 'YES' THEN 1.0 ELSE 0.0 END)*100 AS CANCELLATION_RATE
FROM GYM_VISITS;

--- PLAN - WISE CANCELLATIONS ---

SELECT 
  MEMBERSHIPPLAN,
  AVG(CASE WHEN CANCELLED = 'YES' THEN 1.0 ELSE 0.0 END)*100 AS CANCELLATION_RATE 
FROM GYM_VISITS
GROUP BY MEMBERSHIPPLAN
ORDER BY CANCELLATION_RATE DESC;

--- TRAINING IMPACT ---

SELECT 
 CANCELLED,
 AVG(PERSONAL_TRAINING_SESSIONS) AS AVG_TRAINING_SESSIONS
FROM GYM_VISITS
GROUP BY CANCELLED
ORDER BY AVG_TRAINING_SESSIONS DESC;

--- HIGH - RISK MEMBERS ---

SELECT * 
FROM GYM_VISITS
WHERE GYMVISITS_PERMONTH<=5
 AND FITNESSRATING<=2;

--- LOW - RISK MEMBERS ---

SELECT *
FROM GYM_VISITS
WHERE GYMVISITS_PERMONTH>5
 AND FITNESSRATING<=10;

--- REVENUE BY MEMBERSHIPPLAN_PLANTYPE ---

SELECT 
 MEMBERSHIPPLAN,
 SUM(MONTHLYFEE) AS TOTAL_FEE
FROM GYM_VISITS
GROUP BY MEMBERSHIPPLAN
ORDER BY TOTAL_FEE DESC;
