--- CREATE TABLE ---

CREATE TABLE EMPLOYEES(
EMPID INT PRIMARY KEY,
AGE INT,
DEPARTMENT VARCHAR(10),
JOBROLE VARCHAR(10),
SALARY INT,
YEARSATCOMPANY INT,
WORKHOURSPERWEEK INT,
ATTRITION VARCHAR(10)
);

--- INSERT VALUES ---

INSERT INTO EMPLOYEES VALUES
(1,25,'SALES','EXECUTIVE',30000,1,45,'YES'),
(2,30,'IT','DEVELOPER',60000,4,40,'NO'),
(3,28,'HR','MANAGER',50000,3,42,'NO'),
(4,35,'IT','DEVELOPER',65000,6,50,'YES'),
(5,40,'SALES','MANAGER',70000,10,48,'NO'),
(6,26,'HR','EXECUTIVE',32000,2,44,'YES'),
(7,32,'IT','DEVELOPER',62000,5,41,'NO'),
(8,29,'SALES','EXECUTIVE',35000,2,46,'YES'),
(9,45,'HR','MANAGER',80000,12,38,'NO'),
(10,27,'IT','DEVELOPER',58000,3,43,'YES')

--- SEE WHOLE DATA ---

SELECT * FROM EMPLOYEES;

--- ATTRITION ANALYSIS ---

SELECT 
  COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END)*100.0/COUNT(*) AS ATTRITION_RATE
FROM EMPLOYEES;

--- DEPARTMENT ANALYSIS ---

SELECT 
  DEPARTMENT,
  SUM(CASE WHEN ATTRITION = 'YES' THEN 1 ELSE 0 END) AS ATTRITION_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY ATTRITION_COUNT DESC;

--- SALARY ANALYSIS ---

SELECT 
 ATTRITION,
 AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY ATTRITION 
ORDER BY AVG_SALARY DESC;

--- SALARY BY JOB ROLE ---

SELECT
  JOBROLE,
  SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY JOBROLE
ORDER BY TOTAL_SALARY DESC;

--- JOBROLE BY WORKHOURS ---

SELECT
  JOBROLE,
  AVG(WORKHOURSPERWEEK) AS AVG_WORKHOURS
FROM EMPLOYEES
GROUP BY JOBROLE
ORDER BY AVG_WORKHOURS DESC;
