--- CRAETE DATABASE---

CREATE DATABASE TASKS;

--- CREATE TABLE ---

CREATE TABLE BOOKINGS(
BOOKINGID INT PRIMARY KEY,
HOTELTYPE VARCHAR(20),
LEADTIMEDAYS INT,
STAYDURATION INT,
GUESTS INT,
BOOKINGCHANNEL VARCHAR(20),
AVGDAILYRATE INT,
CANCELLED VARCHAR(20)
);

--- INSERT DATA ---

INSERT INTO BOOKINGS VALUES
(8001,'RESORT',30,3,2,'ONLINE',5000,'NO'),
(8002,'CITY HOTEL',60,2,1,'AGENT',4000,'YES'),
(8003,'RESORT',10,5,4,'DIRECT',6000,'NO'),
(8004,'CITY HOTEL',90,1,1,'ONLINE',3500,'YES'),
(8005,'RESORT',20,4,3,'DIRECT',5500,'NO'),
(8006,'CITY HOTEL',75,2,2,'AGENT',4200,'YES'),
(8007,'RESORT',15,3,2,'ONLINE',5200,'NO'),
(8008,'CITY HOTEL',100,1,1,'AGENT',3000,'YES'),
(8009,'RESORT',25,4,3,'DIRECT',5800,'NO'),
(8010,'CITY HOTEL',80,2,2,'ONLINE',3900,'YES')

--- VIEW DATA ---

SELECT * FROM BOOKINGS;

--- CANCELFLAG ---

SELECT 
 COUNT(CASE WHEN CANCELLED = 'YES' THEN 1 END)*100.0/COUNT(*) AS CANCEL_RATE
FROM BOOKINGS;

--- BY HOTELTYPE ---

SELECT 
 HOTELTYPE,
 COUNT(CASE WHEN CANCELLED = 'YES' THEN 1 ELSE 0 END) AS CANCEL_RATE
FROM BOOKINGS
GROUP BY HOTELTYPE
ORDER BY CANCEL_RATE DESC;

--- REVENUE POTENTIAL BY HOTEL TYPE ---

SELECT 
 HOTELTYPE,
 SUM(STAYDURATION*AVGDAILYRATE) AS REVENUE_POTENTIAL
FROM BOOKINGS
GROUP BY HOTELTYPE
ORDER BY REVENUE_POTENTIAL DESC;

--- LEAD TIME IMPACT ---

SELECT 
  AVG(LEADTIMEDAYS) AS AVG_LEAD_CANCELLED
FROM BOOKINGS
WHERE CANCELLED = 'YES';

--- HIGH - RISK BOOKINGS ---

SELECT *
FROM BOOKINGS
WHERE LEADTIMEDAYS >60;

--- MEDIUM - RISK BOOKINGS ---

SELECT *
FROM BOOKINGS
WHERE LEADTIMEDAYS <=60;

--- LOW - RISK BOOKINGS ---

SELECT *
FROM BOOKINGS
WHERE LEADTIMEDAYS <=20;

