----CREATE TABLE ----

CREATE TABLE FOOD_ORDERS(
ORDERID INT PRIMARY KEY,
ORDERDATE DATE,
CITY VARCHAR(20),
RESTAURANT VARCHAR(20),
ORDERVALUE INT,
DELIVERYTIME_MIN INT,
DISCOUNT INT,
PAYMENTMETHOD VARCHAR(20),
CUSTOMERRATING FLOAT
);

---- INSERT VALUES INTO IT ----
INSERT INTO FOOD_ORDERS VALUES
(9001,'2026-04-06','DELHI','SPICE HUB',450,32,40,'UPI',4.5),
(9002,'2026-04-06','MUMBAI','BURGER TOWN',320,28,20,'CARD',4.2),
(9003,'2026-04-07','BANGALORE','PIZZA POINT',600,40,60,'UPI',4.7),
(9004,'2026-04-07','DELHI','SPICE HUB',380,35,30,'CASH',4.3),
(9005,'2026-04-08','HYDERABAD','BIRYANI HOUSE',520,45,50,'UPI',4.6),
(9006,'2026-04-08','MUMBAI','BURGER TOWN',290,25,0,'CARD',4.0),
(9007,'2026-04-09','BANGALORE','PIZZA POINT',640,42,70,'UPI',4.8),
(9008,'2026-04-09','HYDERABAD','BIRYANI HOUSE',470,38,40,'CASH',4.4),
(9009,'2026-04-10','DELHI','SPICE HUB',510,36,45,'CARD',4.6),
(9010,'2026-04-10','MUMBAI','BURGER TOWN',350,27,25,'UPI',4.1)

---- VIEW WHOLE DATA ----

SELECT * FROM FOOD_ORDERS;

---- CALCULATE TOTAL NETREVENUE ----

SELECT
  SUM(ORDERVALUE-DISCOUNT) AS NETREVENUE
FROM FOOD_ORDERS;

---- RESTAURANT PERFORMANCE ----

SELECT
  RESTAURANT,
  SUM(ORDERVALUE-DISCOUNT) AS NETREVENUE
FROM FOOD_ORDERS
GROUP BY RESTAURANT
ORDER BY NETREVENUE DESC;

---- DELIVERY PERFORMANCE ----

SELECT 
  CITY,
  AVG(DELIVERYTIME_MIN) AS AVG_DELIVERY
FROM FOOD_ORDERS
GROUP BY CITY
ORDER BY AVG_DELIVERY DESC;

---- RATING ANALYSIS ----

SELECT 
  RESTAURANT,
  ROUND(AVG(CUSTOMERRATING),2) AS AVG_CUSTOMER_RATING
FROM FOOD_ORDERS
GROUP BY RESTAURANT
ORDER BY AVG_CUSTOMER_RATING DESC;

---- REVENUE BY CITY ----

SELECT
  CITY,
  SUM(ORDERVALUE-DISCOUNT) AS NETREVENUE
FROM FOOD_ORDERS
GROUP BY CITY
ORDER BY NETREVENUE DESC;

---- REVENUE BY PAYMENT METHOD ----

SELECT
  PAYMENTMETHOD,
  SUM(ORDERVALUE-DISCOUNT) AS NETREVENUE
FROM FOOD_ORDERS
GROUP BY PAYMENTMETHOD
ORDER BY NETREVENUE;

---- REVENUE BY ORDER DATE ----

SELECT
  ORDERDATE,
  SUM(ORDERVALUE-DISCOUNT) AS NETREVENUE
FROM FOOD_ORDERS
GROUP BY ORDERDATE;

---- REVENUE BY ORDER ID ----

SELECT
  ORDERID,
  SUM(ORDERVALUE-DISCOUNT) AS NETREVENUE
FROM FOOD_ORDERS
GROUP BY ORDERID;

