--- CREATE TABLE ---

CREATE TABLE VISITS(
VISITID INT PRIMARY KEY,
DEPARTMENT VARCHAR(20),
DOCTORID CHAR(2),
PATIENTSPERHOUR INT,
AVGCONSULTTIME_MINS INT,
WAITTIME_MINS INT,
DAYTYPE VARCHAR(20),
SATISFACTIONSCORE INT
);


--- INSERT DATA INTO THE TABLE ---

INSERT INTO VISITS VALUES
(10001,'CARDIOLOGY','D1',6,10,25,'WEEKDAY',4),
(10002,'ORTHOPEDICS','D2',5,12,30,'WEEKDAY',3),
(10003,'GENERAL','D3',8,8,20,'WEEKEND',4),
(10004,'CARDIOLOGY','D1',7,11,35,'WEEKDAY',2),
(10005,'ORTHOPEDICS','D2',4,15,40,'WEEKEND',2),
(10006,'GENERAL','D3',9,7,15,'WEEKDAY',5),
(10007,'CARDIOLOGY','D1',6,10,28,'WEEKEND',3),
(10008,'ORTHOPEDICS','D2',5,13,32,'WEEKDAY',3),
(10009,'GENERAL','D3',8,9,18,'WEEKEND',4),
(10010,'CARDIOLOGY','D1',7,11,38,'WEEKDAY',2)

--- VIEW DATA ---

SELECT * FROM VISITS;

--- AVG WAITTIME ---

SELECT
  DEPARTMENT,
  AVG(WAITTIME_MINS) AS AVG_WAIT
FROM VISITS
GROUP BY DEPARTMENT
ORDER BY AVG_WAIT DESC;

--- DOCTOR WORKLOAD ---

SELECT 
  DOCTORID,
  AVG(PATIENTSPERHOUR) AS AVG_PATIENTS
FROM VISITS
GROUP BY DOCTORID
ORDER BY AVG_PATIENTS DESC;

--- SATISFACTION IMPACT ---

SELECT 
  AVG(SATISFACTIONSCORE) AS AVG_SATISFACTION
FROM VISITS
WHERE WAITTIME_MINS>30;

--- HIGH DELAY CASES ---

SELECT *
FROM VISITS
WHERE WAITTIME_MINS>=35;

--- MEDIUM DELAY CASES ---

SELECT *
FROM VISITS
WHERE WAITTIME_MINS<=32;

--- LOW DELAY CASES ---

SELECT *
FROM VISITS
WHERE WAITTIME_MINS<=20;

