
--- CREATE TABLE ---

CREATE TABLE STOCKS(
PRODUCTID INT PRIMARY KEY,
PRODUCT VARCHAR(20),
CATEGORY VARCHAR(20),
WAREHOUSE VARCHAR(3),
STOCKQTY INT,
REORDERLEVEL INT,
UNITSSOLD_LAST30DAYS INT,
SUPPLIERLEAD_TIMEDAYS INT
);

--- INSERT VALUES INTO TABLE ---

INSERT INTO STOCKS VALUES
(1001,'LAPTOP','ELECTRONICS','WH1',50,20,30,7),
(1002,'MOUSE','ELECTRONICS','WH1',200,50,120,3),
(1003,'CHAIR','FURNITURE','WH2',80,40,20,10),
(1004,'DESK','FURNITURE','WH2',30,25,10,12),
(1005,'MONITOR','ELECTRONICS','WH1',60,30,25,8),
(1006,'KEYBOARD','ELECTRONICS','WH3',150,40,90,5),
(1007,'TABLE','FURNITURE','WH2',25,20,5,15),
(1008,'PRINTER','ELECTRONICS','WH3',40,15,8,10),
(1009,'SOFA','FURNITURE','WH2',10,10,2,20),
(1010,'ROUTER','ELECTRONICS','WH1',120,60,70,6)

--- SEE WHOLE DATA ---

SELECT * FROM STOCKS;

--- LOW STOCK PRODUCTS ---

SELECT 
  PRODUCT,
  STOCKQTY,
  REORDERLEVEL
FROM STOCKS
WHERE STOCKQTY<REORDERLEVEL;

--- OVER STOCK PRODUCTS ---

SELECT 
 PRODUCT,
 STOCKQTY,
 UNITSSOLD_LAST30DAYS
FROM STOCKS
WHERE STOCKQTY>UNITSSOLD_LAST30DAYS*2;

--- WAREHOUSE PERFORMANCE ---

SELECT
 WAREHOUSE,
 SUM(UNITSSOLD_LAST30DAYS) AS TOTAL_SALES
FROM STOCKS
GROUP BY WAREHOUSE
ORDER BY TOTAL_SALES DESC;

--- PRODUCT PERFORMANCE ---

SELECT 
 PRODUCT,
 SUM(UNITSSOLD_LAST30DAYS) AS TOTAL_SALES
FROM STOCKS
GROUP BY PRODUCT
ORDER BY TOTAL_SALES DESC;

--- UNITSSOLD BY CATEGORY ---

SELECT 
 CATEGORY,
 SUM(UNITSSOLD_LAST30DAYS) AS TOTAL_UNITS
FROM STOCKS
GROUP BY CATEGORY
ORDER BY TOTAL_UNITS DESC;

--- AVG SUPPLIERLEAD DAYS BY PRODUCT ---

SELECT 
  PRODUCT,
  AVG(SUPPLIERLEAD_TIMEDAYS) AS AVG_SUPPLIERLEAD_TIMEDAYS
FROM STOCKS
GROUP BY PRODUCT
ORDER BY AVG_SUPPLIERLEAD_TIMEDAYS DESC;