--- CREATE TABLE ---

CREATE TABLE TICKETS(
TICKETID INT PRIMARY KEY,
DATE DATE,
ISSUETYPE VARCHAR(20),
PRIORITY VARCHAR(20),
RESOLUTIONTIME_HOURS INT,
AGENT CHAR(3),
CUSTOMERSATISFACTION INT,
ESCALATED VARCHAR(10)
);

--- INSERT DATA INTO IT ---

INSERT INTO TICKETS VALUES

(3001,'2026-04-10','LOGIN ISSUE','HIGH',5,'A1',3,'YES'),
(3002,'2026-04-10','PAYMENT ISSUE','MEDIUM',3,'A2',4,'NO'),
(3003,'2026-04-11','BUG REPORT','HIGH',8,'A3',2,'YES'),
(3004,'2026-04-11','FEATURE REQUEST','LOW',2,'A1',5,'NO'),
(3005,'2026-04-12','LOGIN ISSUE','MEDIUM',4,'A2',3,'NO'),
(3006,'2026-04-12','PAYMENT ISSUE','HIGH',6,'A3',2,'YES'),
(3007,'2026-04-13','BUG REPORT','HIGH',7,'A1',2,'YES'),
(3008,'2026-04-13','FEATURE REQUEST','LOW',1,'A2',5,'NO'),
(3009,'2026-04-14','LOGIN ISSUE','MEDIUM',3,'A3',4,'NO'),
(3010,'2026-04-14','PAYMENT ISSUE','HIGH',6,'A1',2,'YES')

--- SEE WHOLE DATA ---

SELECT * FROM TICKETS;

--- AVG RESOLUTION TIME ---

SELECT
 ISSUETYPE,
 ROUND(AVG(CAST(RESOLUTIONTIME_HOURS AS FLOAT)),2) AS AVG_RESOLUTIONTIME
FROM TICKETS
GROUP BY ISSUETYPE
ORDER BY AVG_RESOLUTIONTIME DESC;

--- ESCALATION RATE ---

SELECT
  COUNT(CASE WHEN ESCALATED = 'YES' THEN 1 END)*100.0/COUNT(*) AS ESCALATION_RATE
FROM TICKETS;

--- NON ESCALATION RATE ---

SELECT 
  COUNT(CASE WHEN ESCALATED = 'NO' THEN 0 END) AS NON_ESCALATION_RATE
FROM TICKETS;

--- TICKET COUNT BY AGENT ---

SELECT
  AGENT,
  COUNT(TICKETID) AS TOTAL_TICKETS
FROM TICKETS
GROUP BY AGENT
ORDER BY TOTAL_TICKETS DESC;

--- AGENT PERFORMANCE ---

SELECT 
  AGENT,
  AVG(CUSTOMERSATISFACTION) AS CUSTOMER_RATING
FROM TICKETS
GROUP BY AGENT
ORDER BY CUSTOMER_RATING DESC;

--- HIGH PRIORITY ISSUES ---

SELECT *
FROM TICKETS
WHERE PRIORITY = 'HIGH';

--- MEDIUM PRIORITY ISSUES ---

SELECT *
FROM TICKETS
WHERE PRIORITY = 'MEDIUM';

--- LOW PRIORITY ISSUES ---

SELECT *
FROM TICKETS
WHERE PRIORITY='LOW';


