--- CREATE TABLE ---

CREATE TABLE SESSIONS(
SESSIONID INT PRIMARY KEY,
DATE DATE,
TRAFFICSOURCE VARCHAR(20),
DEVICE VARCHAR(20),
PAGESVIEWED INT,
TIMEONSITE_SEC INT,
ADDEDTOCART VARCHAR(20),
PURCHASED VARCHAR(20)
);

--- INSERT VALUES INTO IT ---

INSERT INTO SESSIONS VALUES

(5001,'2026-04-10','ORGANIC','MOBILE',5,180,'YES','NO'),
(5002,'2026-04-10','PAID ADS','DESKTOP',8,300,'YES','YES'),
(5003,'2026-04-11','DIRECT','MOBILE',3,90,'NO','NO'),
(5004,'2026-04-11','ORGANIC','DESKTOP',6,210,'YES','YES'),
(5005,'2026-04-12','PAID ADS','MOBILE',4,150,'YES','NO'),
(5006,'2026-04-12','DIRECT','DESKTOP',7,250,'NO','NO'),
(5007,'2026-04-13','ORGANIC','MOBILE',5,200,'YES','YES'),
(5008,'2026-04-13','PAID ADS','DESKTOP',9,320,'YES','YES'),
(5009,'2026-04-14','DIRECT','MOBILE',2,60,'NO','NO'),
(5010,'2026-04-14','ORGANIC','DESKTOP',6,220,'YES','YES')

--- VIEW DATA ---

SELECT * FROM SESSIONS;

--- OVERALL CONVERSION ---

SELECT 
  COUNT(CASE WHEN PURCHASED = 'YES' THEN 1 END)*100.0/COUNT(*) AS CONVERSION_RATE
FROM SESSIONS;

--- TRAFFICSOURCE PERFORMANCE ---

SELECT 
  TRAFFICSOURCE,
  COUNT(*) AS TOTAL_SESSIONS,
  SUM(CASE WHEN PURCHASED = 'YES' THEN 1 ELSE 0 END) AS PURCHASES
FROM SESSIONS
GROUP BY TRAFFICSOURCE
ORDER BY PURCHASES;

--- CART DROP-OFF ---

SELECT
  COUNT(CASE WHEN ADDEDTOCART = 'YES' THEN 1 END) AS CARTS,
  COUNT(CASE WHEN PURCHASED = 'YES' THEN 1 END) AS PURCHASES
FROM SESSIONS;

--- AVG TIMEONSITE_SEC ---

SELECT 
 TRAFFICSOURCE,
 AVG(TIMEONSITE_SEC) AS AVG_TIMEONSITE_SEC
FROM SESSIONS
GROUP BY TRAFFICSOURCE
ORDER BY AVG_TIMEONSITE_SEC DESC;

--- PURCHASES BY DEVICE ---

SELECT
 DEVICE,
 COUNT(CASE WHEN PURCHASED = 'YES' THEN 1 END) AS PURCHASES
FROM SESSIONS
GROUP BY DEVICE
ORDER BY PURCHASES DESC;

--- PURCHASES BY DATE ---

SELECT 
  DATE,
  COUNT(CASE WHEN PURCHASED='YES' THEN 1 END) AS PURCHASES
FROM SESSIONS
GROUP BY DATE;