--- CREATE TABLE ---

CREATE TABLE ECOMMERCE(
ORDERID VARCHAR(10) PRIMARY KEY,
PRODUCTCATEGORY VARCHAR(20),
ORDERVALUE INT,
DELIVERYDAYS INT,
CUSTOMERRATING INT,
RETURNED VARCHAR(10),
PAYMENTMETHOD VARCHAR(10),
DISCOUNTPERCENT INT
);

--- INSERT VALUES INTO IT ---

INSERT INTO ECOMMERCE VALUES

('E1001','ELECTRONICS',45000,6,2,'YES','COD',15),
('E1002','FASHION',3200,3,5,'NO','UPI',30),
('E1003','HOME DECOR',5400,5,4,'NO','CARD',10),
('E1004','ELECTRONICS',38000,8,1,'YES','COD',20),
('E1005','FASHION',2700,2,5,'NO','UPI',35),
('E1006','GROCERY',1800,1,4,'NO','WALLET',5),
('E1007','ELECTRONICS',52000,9,2,'YES','CARD',25),
('E1008','FASHION',4100,4,3,'NO','UPI',15),
('E1009','HOME DECOR',6200,6,2,'YES','COD',12),
('E1010','ELECTRONICS',47000,10,1,'YES','CARD',30)

--- SEE WHOLE DATA ---

SELECT * FROM ECOMMERCE;

--- OVERALL RETURN RATE ---

SELECT
AVG(CASE WHEN RETURNED ='YES' THEN 1.0 ELSE 0.0 END)*100 AS RETURN_RATE
FROM ECOMMERCE;

--- CATEGORY-WISE RETURNES ---

SELECT
PRODUCTCATEGORY,
AVG(CASE WHEN RETURNED ='YES' THEN 1.0 ELSE 0.0 END)*100 AS RETURN_RATE 
FROM ECOMMERCE
GROUP BY PRODUCTCATEGORY
ORDER BY RETURN_RATE DESC;

--- DELIVERY IMPACT ON RETURENS ---

SELECT
RETURNED,
AVG(DELIVERYDAYS) AS AVG_DELIVERY_DAYS
FROM ECOMMERCE
GROUP BY RETURNED
ORDER BY AVG_DELIVERY_DAYS DESC;

--- DISCOUNTPERCENT BY PAYMENTMETHOD ---

SELECT 
PAYMENTMETHOD,
AVG(DISCOUNTPERCENT) AS AVG_DISCOUNT
FROM ECOMMERCE
GROUP BY PAYMENTMETHOD
ORDER BY AVG_DISCOUNT DESC;

--- HIGH-RISK ORDERS ---

SELECT *
FROM ECOMMERCE
WHERE CUSTOMERRATING<=2
 AND DELIVERYDAYS>=7;

--- MEDIUM-RISK ORDERS ---

SELECT *
FROM ECOMMERCE
WHERE CUSTOMERRATING<=4
 AND DELIVERYDAYS<=6;

--- LOW-RISK ORDERS ---

SELECT * 
FROM ECOMMERCE
WHERE CUSTOMERRATING=5
 AND DELIVERYDAYS<=3;
