---- CREATE TABLE ----

CREATE TABLE RIDES(
TRIPID INT PRIMARY KEY,
TRIPDATE DATE,
CITY VARCHAR(20),
VEHICLETYPE VARCHAR(20),
DISTANCE_KM INT,
FAREPERKM INT,
SURGE_MULTIPLIER FLOAT,
DRIVER_RATING FLOAT,
PAYMENT_MODE VARCHAR(20)
);

---- INSERT VALUES INTO TABLE ----

INSERT INTO RIDES VALUES
(8001,'2026-04-01','DELHI','MINI',8,12,1.0,4.5,'UPI'),
(8002,'2026-04-01','MUMBAI','SEDAN',12,15,1.2,4.7,'CARD'),
(8003,'2026-04-02','BANGALORE','MINI',5,12,1.0,4.2,'CASH'),
(8004,'2026-04-02','DELHI','SUV',15,18,1.5,4.8,'UPI'),
(8005,'2026-04-03','HYDERABAD','MINI',7,12,1.0,4.1,'CASH'),
(8006,'2026-04-03','MUMBAI','SEDAN',10,15,1.3,4.6,'CARD'),
(8007,'2026-04-04','BANGALORE','SUV',18,18,1.6,4.9,'UPI'),
(8008,'2026-04-04','HYDERABAD','MINI',6,12,1.0,4.3,'CASH'),
(8009,'2026-04-05','DELHI','SEDAN',11,15,1.2,4.4,'CARD'),
(8010,'2026-04-05','MUMBAI','MINI',4,12,1.0,4.0,'UPI')

---- SEE WHOLE DATA ----

SELECT * FROM RIDES;

---- CALCUALTE FARE_PRICE / REVENUE ----

SELECT 
 SUM(DISTANCE_KM*FAREPERKM*SURGE_MULTIPLIER) AS REVENUE
FROM RIDES;

---- REVENUE BY CITY ----

SELECT 
 CITY,
 SUM(DISTANCE_KM*FAREPERKM*SURGE_MULTIPLIER) AS REVENUE
FROM RIDES
GROUP BY CITY
ORDER BY REVENUE DESC;

---- AVERAGE RATING ----

SELECT
  VEHICLETYPE,
  AVG(DRIVER_RATING) AS AVG_RATING
FROM RIDES
GROUP BY VEHICLETYPE
ORDER BY AVG_RATING DESC;

---- PEAK SURGE ANALYSIS ----

SELECT
  SURGE_MULTIPLIER,
  COUNT(*) AS TRIP_COUNT
FROM RIDES
GROUP BY SURGE_MULTIPLIER
ORDER BY SURGE_MULTIPLIER DESC;

---- REVENUE BY VEHICLE_TYPE ----

SELECT 
 VEHICLETYPE,
 SUM(DISTANCE_KM*FAREPERKM*SURGE_MULTIPLIER) AS REVENUE
FROM RIDES
GROUP BY VEHICLETYPE
ORDER BY REVENUE DESC;

---- REVENUE BY TRIPDATE ----

SELECT 
 TRIPDATE,
 SUM(DISTANCE_KM*FAREPERKM*SURGE_MULTIPLIER) AS REVENUE
FROM RIDES
GROUP BY TRIPDATE 
ORDER BY TRIPDATE ;

---- REVENUE BY PAYMENT_MODE ----

SELECT 
 PAYMENT_MODE,
 SUM(DISTANCE_KM*FAREPERKM*SURGE_MULTIPLIER) AS REVENUE
FROM RIDES
GROUP BY PAYMENT_MODE
ORDER BY REVENUE ;

