--- CREATE TABLE ---

CREATE TABLE AIRLINE_DATA(
FLIGHT_ID VARCHAR(10) PRIMARY KEY,
ROUTE_TYPE VARCHAR(20),
DELAY_MINUTES INT,
TICKET_PRICE INT,
PASSENGER_SATISFACTION INT,
COMPENSATION_PAID INT,
BAGGAGE_ISSUES VARCHAR(10),
FLIGHT_CANCELLED VARCHAR(10)
);

--- INSERT VALUES INTO IT ---

INSERT INTO AIRLINE_DATA VALUES
('A1001','DOMESTIC',75,5200,2,1800,'YES','NO'),
('A1002','INTERNATIONAL',15,42000,5,0,'NO','NO'),
('A1003','DOMESTIC',30,6800,4,0,'NO','NO'),
('A1004','DOMESTIC',95,4900,1,2500,'YES','NO'),
('A1005','INTERNATIONAL',20,51000,5,0,'NO','NO'),
('A1006','DOMESTIC',50,7200,3,1200,'YES','NO'),
('A1007','INTERNATIONAL',10,47000,5,0,'NO','NO'),
('A1008','DOMESTIC',85,5600,2,2000,'YES','NO'),
('A1009','DOMESTIC',120,6100,1,3200,'YES','YES'),
('A1010','INTERNATIONAL',18,53000,4,0,'NO','NO')

--- VIEW DATA ---

SELECT *
FROM AIRLINE_DATA;

--- AVG DELAYS ---

SELECT ROUTE_TYPE,
AVG(DELAY_MINUTES) AS AVG_DELAY
FROM AIRLINE_DATA
GROUP BY ROUTE_TYPE
ORDER BY AVG_DELAY DESC;

--- COMPENSATION ANALYSIS ---

SELECT 
SUM(COMPENSATION_PAID) AS TOTAL_COMPENSATION
FROM AIRLINE_DATA;

--- COMPENSATION ANALYSIS BY ROUTE TYPE ---

SELECT ROUTE_TYPE,
SUM(COMPENSATION_PAID) AS TOTAL_COMPENSATION
FROM AIRLINE_DATA
GROUP BY ROUTE_TYPE
ORDER BY TOTAL_COMPENSATION DESC;

--- SATISFACTION IMPACT ---

SELECT 
CASE 
WHEN DELAY_MINUTES<=30 THEN 'MINOR DELAY'
WHEN DELAY_MINUTES<=60 THEN 'MODERATE DELAY'
ELSE 'SEVERE DELAY'
END AS DELAY_CATEGORY,
AVG(PASSENGER_SATISFACTION) AS AVG_SATISFACTION
FROM AIRLINE_DATA
GROUP BY 
CASE 
WHEN DELAY_MINUTES<=30 THEN 'MINOR DELAY'
WHEN DELAY_MINUTES<=60 THEN 'MODERATE DELAY'
ELSE 'SEVERE DELAY'
END 
ORDER BY AVG_SATISFACTION DESC;

---TICKET SEGMENT ---

SELECT
CASE 
WHEN TICKET_PRICE<10000 THEN 'ECONOMY'
WHEN TICKET_PRICE<40000 THEN 'BUSINESS'
ELSE 'PREMIUM'
END AS TICKET_PRICE,
AVG(COMPENSATION_PAID) AVG_COMPENSATION
FROM AIRLINE_DATA
GROUP BY
CASE 
WHEN TICKET_PRICE<10000 THEN 'ECONOMY'
WHEN TICKET_PRICE<40000 THEN 'BUSINESS'
ELSE 'PREMIUM'
END
ORDER BY TICKET_PRICE DESC;

--- HIGH-RISK FLIGHTS ---

SELECT *
FROM AIRLINE_DATA
WHERE DELAY_MINUTES>60
AND PASSENGER_SATISFACTION<=2;

--- LOW-RISK FLIGHTS ---

SELECT *
FROM AIRLINE_DATA
WHERE DELAY_MINUTES<=60
AND PASSENGER_SATISFACTION>2;