
--- CREATE TABLE ---

CREATE TABLE COURSES(
STUDENTID VARCHAR(10) PRIMARY KEY,
COURSECATEGORY VARCHAR(20),
COURSEPRICE INT,
WATCHTIME_HOURS INT,
ASSIGNMENTSCOMPLETED INT,
STUDENTRATING INT,
REFUNDREQUESTED VARCHAR(5),
COURSECOMPLETED VARCHAR(5)
);

---INSERT DATA INTO TABLE ---

INSERT INTO COURSES VALUES

('L1001','DATA SCIENCE',4999,8,2,2,'YES','NO'),
('L1002','PROGRAMMING',6999,42,10,5,'NO','YES'),
('L1003','DESIGN',3499,18,5,4,'NO','YES'),
('L1004','DATA SCIENCE',5999,6,1,1,'YES','NO'),
('L1005','MARKETING',2999,25,7,5,'NO','YES'),
('L1006','PROGRAMMING',6499,20,4,3,'NO','NO'),
('L1007','DESIGN',3999,15,3,3,'YES','NO'),
('L1008','MARKETING',2799,28,8,5,'NO','YES'),
('L1009','DATA SCIENCE',5499,10,2,2,'YES','NO'),
('L1010','PROGRAMMING',7499,45,12,5,'NO','YES')

--- VIEW DATA ---

SELECT * FROM COURSES;

--- AVG WATCHTIME_HOURS BY COURSECATEGORY ---

SELECT 
COURSECATEGORY,
AVG(WATCHTIME_HOURS) AS AVG_WATCH_HOURS
FROM COURSES
GROUP BY COURSECATEGORY
ORDER BY AVG_WATCH_HOURS DESC;

--- AVG COURSEFEES BY COURSECATEGORY ---

SELECT 
COURSECATEGORY,
AVG(COURSEPRICE) AS AVG_COURSEPRICE
FROM COURSES
GROUP BY COURSECATEGORY
ORDER BY AVG_COURSEPRICE DESC;

-- AVG STUDENTRATING BY ENGAGEMENTLEVEL ---

SELECT 
CASE 
WHEN WATCHTIME_HOURS<=8 THEN 'LOW'
WHEN WATCHTIME_HOURS<=24 THEN 'MODERATE'
ELSE 'HIGH'
END AS ENGAGEMENT_LEVEL,
AVG(STUDENTRATING) AS AVG_STUDENTRATING
FROM COURSES
GROUP BY 
CASE 
WHEN WATCHTIME_HOURS<=8 THEN 'LOW'
WHEN WATCHTIME_HOURS<=24 THEN 'MODERATE'
ELSE 'HIGH'
END
ORDER BY AVG_STUDENTRATING DESC;

--- COMPLETION RATE BY COURSECATEGORY ---

SELECT 
COURSECATEGORY,
SUM(CASE WHEN COURSECOMPLETED = 'YES' THEN 1 ELSE 0 END) AS COMPLETION_RATE
FROM COURSES
GROUP BY COURSECATEGORY
ORDER BY COMPLETION_RATE DESC;

--- REFUND RATE BY COURSECATEGORY ---

SELECT 
COURSECATEGORY,
SUM(CASE WHEN REFUNDREQUESTED = 'YES' THEN 1 ELSE 0 END) AS REFUND_RATE 
FROM COURSES
GROUP BY COURSECATEGORY
ORDER BY REFUND_RATE DESC;

